apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer #NodePort (can be acess from outside the cluster with the node ip address, which is combersome) | ClusterIP(Node to be access only from inside the cluster)
  ports:
    - protocol: TCP
      port: 8000 #outside port
      targetPort: 8000 # port in the pod/container