apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: clonit/k8s-tasks-api:v1
          env:
            - name: AUTH_URL
              # value: localhost | Using env to connect to service
              value: 'auth-service.default' # Using default namespace kubectl get namespaces
            - name: TASKS_FOLDER
              value: tasks