apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: clonit/k8s-users-api:v1
          env:
            - name: AUTH_URL
              # value: localhost | Using env to connect to service
              value: 'auth-service.default' # Using default namespace kubectl get namespaces