services:
  mongodb:
    image: 'mongo:5.0'
    restart: unless-stopped
    volumes:
      - data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=
    #   - MONGO_INITDB_ROOT_PASSWORD=
    env_file:
      - ./mongo.env
  backend:
    # image: 'imageName'
    # build: ./backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
      # args:
      #   - name=value
    ports:
      - '80:80'
    volumes:
      - ./backend/logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/backend.env
    depends_on:
      - mongodb
  frontend:
    restart: unless-stopped
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: